### ISSUE TITLE
Implement stock elevators into SS codebase and improve with SIF

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#176]
- [ ] ls_apartments1
- [ ] ls_apartments2
- [ ] ls_beachside
- [ ] sf_zombotech

Started work on apartments1.

**Comment by viruxe** [comment]
Wouldn't make more sense to just leave these as filterscripts? They worked fine in the previous server.

**Comment by Southclaw** [comment]
It's not much work and I want to make the elevator buttons SIF buttons to be consistent with everything else. Filterscript related things always turn out buggy on restarts anyway (object IDs, etc)
