### ISSUE TITLE
Ideas for New Items

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#187]
Existing items with no use:
- [ ] item_Spanner
- [ ] item_OilCan
- [ ] item_RadioBox
- [ ] item_Microphone
- [ ] item_Beanie
- [ ] item_BoxingGloves
- [ ] item_Briquettes
- [ ] item_RedPanel
- [ ] item_Padlock

Created with craft-construct:
- [ ] 19641: wood barb fence
- [ ] 19865: wood fence
- [ ] 19868: mesh barb fence
- [ ] 19869: mesh fence
- [ ] 19157: metal frame for building
- [ ] 19871: metal pole for holding something
- [ ] 19900: tool cabinet for storage
- [ ] 19618: safe for storage
- [x] 11729: locker for storage (fallout 3 style!)
- [ ] 19903: some kind of super high level processing machine
- [x] 958: some kind of processing machine (wood?)
- [x] 943: another kind of processing machine (metal?)
- [x] 920: smaller generator thing, low level processing?
- [ ] 919/1353: ac machine
- [x] 936: constructable workbench!

Created with regular crafting:
- [ ] 964: constructible metal box for safe storage
- [ ] 11743: some kind of... coffee machine

Unspecified or not created via crafting (only spawns in world)
- [x] 19812: drums for liquid (oil/fuel resource?)
- [ ] 1719 small computer type device
- [ ] 1958 control terminal
- [ ] 3067 metal frame
- [ ] 19920 small remote device

Useful Model IDs that could one day become items:

- 1656 cuboid shape, carry item
- 2422 computer terminal
- 1898 small spin clicker
- 1899 very small single chip
- 1901 small blue chips stack
- 1960 record
- 2060 sandbag
- 2277 picture of a cat
- 2351 detonator thing
- 2352 t shaped small obj
- 2590 spikey hook, schythe?
- 2226 hifi
- 2231 speaker/small box shape
- 2232 slightly bigger speaker
- 2324 short cylinder (retexture)
- 2388 short pole type thing
- 2749 small long cylinder (also 2752)
- 2751 wide short cylinder
- 2750 hair dryer/gun shape
- 2780 small grey box with handle
- 2894 book
- 2961 small red keypad-like thing
- 2983 pipe valve
- 3025 piece of scap metal pole/frame
- 3070 goggles
- 19896 cigarettes
- 19874 soap
- 19873 toilet paper
- 19871 metal pole stand thing
- 19917 large engine
- 19844 small metal panel
- 19845 small metal panel
- 19846 small metal panel
- 19347 for dogmeat...
- 19314 horns (combine with sledgehammer for pic-axe!)

**Comment by Southclaw** [comment]
Some items should be removed from loot rotation or lowered in chance and made craftable.
- Sign (remove)
- Storage safeboxes (lower)
- Fishing Rod (lower)
- Tent pack (lower)

**Comment by Southclaws** [comment]
Added items without a use.

**Comment by Patrik356b** [comment]
Perhaps the spanner could be used as an alternative to the screwdriver?
