### ISSUE TITLE
Hats/masks that need skin offsets

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#191]
- [ ] item_StrawHat
- [x] item_WitchesHat
- [ ] item_CaptainsCap
- [ ] item_Bucket
- [ ] item_SwatHelmet
- [ ] item_PussyMask
- [ ] item_DevilMask

**Comment by viruxe** [comment]
Perhaps I can help you with this one? Wasn't there a tool already made to get these offsets?

**Comment by Southclaw** [comment]
Yeah it's a filterscript called "attachedit". It's quite a lot of work though since there are 17 skins. 7 new hats means 17*7: 119 offsets to be made! (this is why I don't add hats very often)

**Comment by viruxe** [comment]
This also reminds me that there should be more skins. It happens quite often that players around you all have the same skins.

I'll take a look at that filterscript and new hats.

**Comment by Southclaw** [comment]
I'll see about adding new skins at some point, it will be either new skins or new hats but probably not both.

**Comment by Southclaw** [comment]
Hey, I'm finally doing this @viruxe :p #307

**Comment by Dayvison** [comment]
Maybe this can help? http://forum.sa-mp.com/showthread.php?p=3791767

**Comment by Southclaw** [comment]
That looks useful, thanks! I was thinking of using the current hat coordinates to build a generic offset library since it only needs to cover the current skins. I'll look into integrating this data into the attachment system.
