### ISSUE TITLE
Water treatment

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#234]
The final objective to fulfil the original goal of making living on an oil rig/island possible is water.

The Plant Pot system can give a player food but it's useless without water. The next (and probably final) machine to be implemented will be a water treatment machine that will convert seawater (and other types of non-pure water) into pure water.

It will either require to be built on/in water or just take impure water as an input and generate pure water regardless of the location (probably easier).

**Comment by kadaradam** [comment]
if you choose to generate water on ground (2nd), this where the bucket would come handy. you could fill up with both purified and non purified water.

**Comment by Southclaw** [comment]
I thought of a fun experiment actually, I might make the machine constructable near water but it generates a line of pipes to the nearest square meter of water so it looks like it's pumping water! Then, in relation to #235 any "liquid container" item that contains dirty water/sea water can be put inside also to be purified.

Or, I could just make two machines, one that pumps water into liquid containers and another that converts it.

(main inspiration for all this nonsense is [minecraft tekkit processing systems](http://vignette1.wikia.nocookie.net/thetekkit/images/b/b0/Pump_(BC).png/revision/latest?cb=20120901232608) which I wasted hours on a few years ago!)
