### ISSUE TITLE
Re-implement Liquid Crafting on top of the new liquid-container module

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#246]
Since this is a generic module that applies the effects to the itemtypes defined by its main `Define` function, the only current way to allow any liquid container to be crafted with any other liquid container would be to use `DefineCraftSet` on every combination of liquid-container item types.

So, this calls for a change to be made in SIF to allow for selections without a defined craft set to still call an event to allow modules like liquid-container to perform their own comparisons and handle the craft.

This will either be done by defining a "temporary" craftset to store the selected items in and passing that to `OnPlayerCraft` or creating a new callback altogether for crafting items not in a defined set.

**Comment by Patrik356b** [comment]
What are you planning to have regarding liquid crafting?

**Comment by Southclaw** [comment]
I haven't really had many ideas yet but some basic ones were written down in the original feature issue #130 

One example is combining "Protein Powder" with water (or any type of juice) to create a more nutritious drink. Other ideas are mostly either healing "potions" or poisons but nothing definite.

I'm also thinking of allow players to "hide" liquids inside others so they can poison a player without them knowing they are drinking poison.

Liquid types are here: https://github.com/Southclaw/ScavengeSurvive/blob/master/gamemodes/sss/core/server/init.pwn#L1666 and liquid container module is here https://github.com/Southclaw/ScavengeSurvive/blob/master/gamemodes/sss/core/item/liquid-container.pwn

**Comment by Patrik356b** [comment]
One idea that comes to mind is purifying water. If you have a liquid container and your near some real water you can fill this to get "dirty water". Using this with a campfire produces "purified water" which is more beneficial upon usage.

**Comment by kadaradam** [comment]
Yeah, I have the same idea, and South already started working on the purifier machine [here](https://github.com/Southclaw/ScavengeSurvive/commit/b342b03e6e5e686664451d560a57d92d73b76503), but that's different.

Water purifier should be simple. People like simple things. Just add an input item and an ouput item. You'd have to get salt water from sea into the canister, and bring it to the purifier machine. The machine would clear the water and pour it into a 2nd canister (output).

Canisters could be filled up with freshwater or seawater, depending where you are.

**Comment by Southclaw** [comment]
I might water cookable on fires/bbqs to purify it too actually, but you lose 25% of the liquid in the process (and can only use metal containers).

**Comment by Patrik356b** [comment]
I had a similar thought

**Comment by Patrik356b** [comment]
It would be nice if Un purified water could be used in some cases also, but has some penalties. 

I. E. Cooking a meal with purified and un purified water makes a 20% stats difference for the crafted meal
