### ISSUE TITLE
Migrate wiki to MDWiki at ss.southcla.ws

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#295]
The existing wiki (http://scavenge-survive.wikia.com/wiki/Main_Page) runs MediaWiki and is less than ideal to keep updated.

I'd like to move the wiki over to GitHub or open up a GitHub pages (http://southclaw.net/ScavengeSurvive) page for it.

I will update the wiki content regardless of whether or not this happens. I'm writing it in Markdown syntax because it's simple and easy (one reason why I wanted to move to GitHub Wiki, it supports Markdown).

**Comment by Southclaws** [comment]
I'm leaning towards MDWiki now: http://dynalon.github.io/mdwiki/#!index.md
I'll likely convert the wikia site to markdown and store the files in the source repo in a wiki directory (I don't like GitHub's wiki branch system really) and set up the webserver to pull from there.

**Comment by viruxe** [comment]
MDWiki seems a good enough alternative for markdown. What exactly do you need help on?

**Comment by Southclaws** [comment]
Mostly just documenting everything at this point, I can handle converting the wikia files to markdown (I'll make a python script probably).

The main thing right now is probably writing a short sentence explaining each item.

To make things easier, a lot of items have no use so those can be skipped. And of course, items that are "grouped" don't need documentation for _every_ item, just what the group as a whole do.

For example, food items probably don't need a page for every single food item right now, they just need a "Food Items" page with a list of food items and a short explanation of what *all* food items do.

The only exception to this is weapons. I think each weapon does need a separate page explaining the weapon's ammunition types, what the player can expect in a gunfight, how many shots to take down someone, etc.

**Comment by Southclaws** [comment]
In fact, I could probably generate these files quickly using the `Define<something>ItemType` functions in `init.pwn`.

**Comment by Southclaws** [comment]
Update: wiki is now live at ss.southcla.ws/mdwiki.html
Repository for editing: https://github.com/Southclaws/ScavengeSurviveWiki

**Comment by Southclaws** [comment]
Sheriffic is helping with this.

**Comment by Virtxmedia** [comment]
I'll also help where I can with this in my spare time.
