### ISSUE TITLE
Collect all Python scripts into a properly formatted package

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#332]
All the little scripts in `misc/` should be put into a proper Python package.

I also want to build some API modules that model the various data structures in SS and provide an interface to accessing the following data stores:

- [x] accounts database
- [x] player data
- [ ] saved world items
- [ ] saved vehicles
- [x] vehicle spawn points
- [x] object placement
- [ ] log data

This could also be used in conjunction with Pawpy (once it's stable and starts to become implemented into SS) for speeding up certain IO operations by taking advantage of concurrent Python function calls.

**Comment by Southclaw** [comment]
This package is now in the `pyss` directory.

the name "pyss" an unintended (yet adequate, given the humour of the GTA series!) side effect of combining "Python" and "SS"...

**Comment by Southclaws** [comment]
Dropping support for Python based stored data such as world items and vehicles for now.
