### ISSUE TITLE
Items such as hats, masks, bags not being removed from player's hands when used

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#333]
When using an object such as backpack, hat etc.
The item does not go away at hand! Can you help?

**Comment by Southclaws** [comment]
(Please use appropriate titles for issue reports, I've edited it for you!)

I've had this reported a couple of times now and I am still mystified. I can't reproduce this at all and all I can say is ensure you're using the latest SIF version. The call to remove the item from the player's hand is in there: https://github.com/Southclaws/ScavengeSurvive/blob/master/gamemodes/sss/core/char/hats.pwn#L119

`RemoveCurrentItem` removes the item from the player's hand, 'GetItemHolder' returns the ID of the player holding the item, `itemid` in this context is the hat item being applied to the player. `RemoveCurrentItem` is right [here](https://github.com/Southclaws/SIF/blob/master/SIF/Item.pwn#L1238) and looks fine. Ensure your code is all up to date and is exactly the same as the code I've linked.

I don't know what can be going wrong here other than just an old SIF version.

**Comment by NegativeIQ** [comment]
I think these is old bug that has been fixed (twice), the one with backpack being duplicated. 
@KoloradoPlay  what version of SS and SIF are you using?

**Comment by viruxe** [comment]
I think this had something to do with "mix-matched" SIF versions and the gamemode itself. Would be nice to know which versions you are using @KoloradoPlay.
