### ISSUE TITLE
Odd error while loading some language files

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#338]
`Malformed line 348 in 'languages/EspaÃ±ol' key contains non-alphabetic character (237:í).`

Problems:
- Character in question is not in a key at all, it's in the value above
- Line is much shorter than 237

This happened once before with the Russian language file but the error appears to have "moved" somehow so this may be a problem with the loader maintaining state of some sort throughout each file load.

**Comment by viruxe** [comment]
I'll have a look at this, since spanish is similar to portuguese.

**Comment by NegativeIQ** [comment]
Is these windows/linux specific?

**Comment by Southclaws** [comment]
The russian issue happened on Windows a while ago and this one I noticed on Linux.

**Comment by Southclaws** [comment]
Never mind, it was a translator making a mistake and trying to translate a key string instead of a value string.
