### ISSUE TITLE
SIF

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#339]
Which version of SIF should I use in Build 1193?

**Comment by Southclaws** [comment]
I'm fairly certain the latest SIF commit or release should work fine but I'm not sure. I've dropped support for build 1193 since merging the `develop` branch to `master` as it's much more stable and easier to work with now.

**Comment by NegativeIQ** [comment]
Just compiled with latest SIF master and SS master without a single problem
