### ISSUE TITLE
Non weapon item information sometimes shows weapon ammo information

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#341]
Some items look like weapons, for example:
Motor (4, 357, FMJ)
Batery (2/0, 357., Tracer)
etc..

**Comment by NegativeIQ** [comment]
Known bug in previous versions (not sure about latest master, but if i run into it again i will confirm) when some additional info about some items (fuel, cooked, ammo, etc...) was misplaced or left over from some items that are no longer exist or located somewhere else.

**Comment by Southclaws** [comment]
Closing, hasn't appeared on current build.
