### ISSUE TITLE
Better visual representation for textlabels

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#342]
I think it would be more intuitive if we would separate actual label text and their values in different colours. Just the values in white would probably suffice.

![sa-mp-000](https://cloud.githubusercontent.com/assets/1616657/21484059/7ec4684e-cb84-11e6-9fb4-aba7e0a612b2.png)

**Comment by Southclaws** [comment]
Yes, I should probably unify colours/styles for these into a consistent set that is recognisable across the game.
