### ISSUE TITLE
Constructions problem

### ISSUE THREAD

**Issue by NegativeIQ** [Southclaws/ScavengeSurvive#344]
If we need some defense item(s) for construction of some items like locker, then its impossible to craft such thing (or maybe its just to hard to place everything on same place in a millimeter). We actually construct defense instead of constructing locker (in these example).

Possible fix: Change order of modules???

**Comment by Southclaws** [comment]
A locker requires 2x MetalFrame and 1 RefinedMetal but these items aren't defence items so I don't really understand what you mean by actually constructing defence instead of locker. I tried to keep defence items out of these craft recipes specifically for this reason.

**Comment by NegativeIQ** [comment]
Oh sorry my bad, i read it as metal panel (idk why)

**Comment by Southclaws** [comment]
The item variable names (and item type uname property) usually represent the original item names but item names get updated sometimes. I admit they can be confusing but it's the "front facing" item name that matters (that's what players see) and some features depend on unames remaining the same so I won't be changing them.
