### ISSUE TITLE
Furniture system

### ISSUE THREAD

**Issue by NegativeIQ** [Southclaws/ScavengeSurvive#346]
Cannot pickup furniture. 
Is it supposed to be like these? 
If it is, after crafting allow it to be moved and rotated like defense?

**Comment by Southclaws** [comment]
Yes, there is a class of items that are "permanent".  There is no suitable carry animation for larger items anyway plus it's a bit weird to simply pick up a table! These are more like luxury base items that players will put time in to placement.

**Comment by NegativeIQ** [comment]
Then i guess it would be a nice thing to show movement system just like the one for defenses...

**Comment by Southclaws** [comment]
It should do, there should be a call to TweakItem in the furniture construction code.

**Comment by NegativeIQ** [comment]
Yeah it does, didnt check it as i was spawning already constructed items.
