### ISSUE TITLE
Uneeded info for the player

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#347]
Maybe just one frase is enough for this?
![sa-mp-001](https://cloud.githubusercontent.com/assets/1616657/21484765/0939af4c-cb90-11e6-917f-315919d53e9f.png)

**Comment by Southclaws** [comment]
Strangely enough, at least from my testing a while ago, it keeps the players connected while the server is stuck in loops loading everything. I think it's something to do with tcp acks and how the server times-out players.

**Comment by viruxe** [comment]
Alright, fair enough.
