### ISSUE TITLE
Can't return to inventory when viewing bag

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#350]
![sa-mp-002](https://cloud.githubusercontent.com/assets/1616657/21486147/e40b42aa-cba6-11e6-8cde-0a6e8358df60.png)

Double clicking that item returns the same menu.

**Comment by Southclaws** [comment]
Admittedly this has been here for a long time and I keep putting off fixing it. It's more of a SIF thing though I think.

**Comment by Southclaws** [comment]
Fixed in SIF.
