### ISSUE TITLE
Incorrect prefab placement

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#352]
Not sure if it's the prefabs fault or not...
![sa-mp-005](https://cloud.githubusercontent.com/assets/1616657/21486232/868dcbdc-cba8-11e6-86fd-686d2712ec5b.png)

**Comment by Southclaws** [comment]
I must have added that house on top of a loot spawn by accident. There are 8k spawns so I might just close this out of laziness...

**Comment by viruxe** [comment]
Could you perhaps add a command to add loot spawn IDs to these labels? Would help to delete these spawns for example.

**Comment by Southclaws** [comment]
That could be done yeah, but there's no reference in the script to an ID. The only way I could think of doing it would be to add the exact coordinates to the label so you could ctrl+f the coordinates in the file: https://github.com/Southclaws/ScavengeSurvive/blob/master/gamemodes/sss/world/zones/bc.pwn#L115-L164

**Comment by viruxe** [comment]
If we can only print coords, maybe have a command write to the chat (so we can copy them from chatlog.txt) the closest spawns within a user defined radius.

**Comment by Southclaws** [comment]
I'll see what I can do
