### ISSUE TITLE
Escape key for exiting inventory or container screens

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#357]
Removed a while ago for reasons, I should re-implement this just because it makes life just a little bit easier when going through boxes and organising items.

**Comment by viruxe** [comment]
:+1:

**Comment by Southclaws** [comment]
If i remember correctly, I removed it because of a weird infinite loop where pressing Esc would trigger a call to OnPlayerSelectPlayerTextDraw which would trigger CancelSelectTextDraw which would again trigger OnPlayerSelectPlayerTextDraw and loop forever. There must be a way around it though because it worked at one point!

**Comment by NicolasScripter** [comment]
Viruxe, can you send your facebook or any contact?

**Comment by Southclaws** [comment]
SS dev chat: dc.southcla.ws
