### ISSUE TITLE
Ice cream - food state

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#361]
Seeing ice cream in the inventory displayed as (un)cooked is a bit awkward. Would there be a possibility to hide food states from particular food items such as this one?

**Comment by Southclaws** [comment]
It should already do that (https://github.com/Southclaws/ScavengeSurvive/blob/master/gamemodes/sss/core/item/food.pwn#L239) so I assume I've just forgotten to set that flag for ice cream in `init.pwn`.

**Comment by Southclaws** [comment]
Which reminds me, `SetItemNameExtra` calls need to use translation strings.
