### ISSUE TITLE
Vehicle saving

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#362]
In regards to vehicle saving where you have text print to the chat every time you save a vehicle, could we consider replacing that with a textdraw that would only display when the inventory (H) is open? So we could avoid spamming the chat box.

**Comment by Southclaws** [comment]
Yep, that was a left over from the `/vsave` testing code, I'll make it into a `ShowActionText` probably.

**Comment by viruxe** [comment]
Yes that would be good but it would also be nice to have either a command or something where we could check what was the last vehicle. It's something easily forgettable but important to know for when a restart is coming up.

**Comment by Southclaws** [comment]
I've added `/veh` for that now.

**Comment by viruxe** [comment]
Perfect.
