### ISSUE TITLE
loot

### ISSUE THREAD

**Issue by NicolasScripter** [Southclaws/ScavengeSurvive#363]
I'm having trouble starting the loots? Can you help?
![loot1](https://cloud.githubusercontent.com/assets/24796828/21524296/401c772a-ccfc-11e6-8363-35b305a422b3.JPG)

![loot2](https://cloud.githubusercontent.com/assets/24796828/21524303/484cde44-ccfc-11e6-8ab0-8cc30e7c80a8.JPG)
![loot3](https://cloud.githubusercontent.com/assets/24796828/21524308/4e81eebc-ccfc-11e6-9260-6e2b0b86f298.JPG)

**Comment by viruxe** [comment]
What do you mean "starting"?

**Comment by Southclaws** [comment]
This is not a questions and answers board, this is for bug reports and tracking new features only.

Use dc.southcla.ws for questions.
