### ISSUE TITLE
Items showing incorrect nameExtra string sometimes

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#368]
Someone reported this but literally just named the report "bug" so I can't be bothered to find it to reopen.

![image](https://cloud.githubusercontent.com/assets/1636971/21543844/e71e9696-cdc1-11e6-96f8-f86b12622fe9.png)

**Comment by viruxe** [comment]
It was issue #354.

**Comment by NegativeIQ** [comment]
It MIGHT have to be something with multiple players since i only remember these to happen when i was playing with friends.

**Comment by Southclaws** [comment]
It might be related to that memory corruption issue yesterday. I highly doubt it's linked to player count, the code isn't dependent on that at all so I'm leaning towards the corruption issue as it's often unpredictable and also only happened when players were using different languages. I'll leave this open during the testing phase and see if anyone notices it again.

**Comment by Southclaws** [comment]
Closing, cannot reproduce.
