### ISSUE TITLE
Few defenses problems (latest master)

### ISSUE THREAD

**Issue by NegativeIQ** [Southclaws/ScavengeSurvive#374]
Defenses positions get messed up when we add motor and open/close them.
For example if we place RustyMetal with a hammer, add motor and open it, it will be opened/closed facing 0 angle (i think its 0).

Also after that its impossible to open/close that defense unless we have something to lift us a bit, or lower defense when placing it in first place. Its like the detection "range" is missing that ~0.2 Z. By the way i was testing on flat terrain.

What i also noticed is that in earlier version the detection range for placing, removing, etc... It was more tolerable and it was perfectly fine to work with, now we need to be in specific position of the (defense) object just to interact with it. For example panels cant be opened unless you are really near the middle of it.

If i find something else i will add it here but if someone could at least confirm these it would be nice.

EDIT: just noticed there was something 4 hours ago about defenses offsets, gonna update as mine is a bit older for some reason

EDIT 2: Ok just re-tested with last commit (Southclaws/ScavengeSurvive@5107a11e33da185464cfba43264d9bed332e53be )

Insulated Panel has the issue not being able to open/close when its UP.
Panels are missing carry offsets or they are wrong.
And that facing angle issue is present

**Comment by Southclaws** [comment]
I'm going to fix this the lazy way: disabling motors on the three defence types that break when rotating.
Carry offsets will be added soon (when I can be bothered, I hate doing offsets!)
What facing angle issue?
I'll try and fix the button heights for all these too.

**Comment by NegativeIQ** [comment]
You misunderstood a little bit, guess i didnt explain it the right way.

Facing angle, i meant that first problem on list, rotation. For example i carry defense and my facing angle is 45deg, if i put it down and set up that defense with hammer it should be rotated at 45deg on Z, and it is. When i add motor and close it (use defense for the first time), it automatically gets rotated on Z to 0. And when i open it again its Z rotation is still at 0 (not 45 like it used to be in first place).

**Comment by Southclaws** [comment]
Ah that, yeah I realised the movement functions weren't setting the item rotation properties only the item's object.

**Comment by Southclaws** [comment]
I've decided to refactor the defence module completely, and I should really use this http://forum.sa-mp.com/showthread.php?t=614857 and support the original defence idea I had years ago which would allow players to build entire standalone buildings. It will take a bit longer but hopefully it will be worth it.
