### ISSUE TITLE
Hunger bar not showing

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#378]
Only started happening since develop>master merge so it can't be a hard one to fix.

**Comment by Southclaws** [comment]
Apparently this fixed itself...?
Works fine on current build.

**Comment by KoloradoPlay** [comment]
fix:
 add:
`TogglePlayerHungerBar(playerid, true); `
in \sss\core\char\food.pwn
hook OnPlayerScriptUpdate(playerid)
