### ISSUE TITLE
Health of the defenses

### ISSUE THREAD

**Issue by FelipeeBR** [Southclaws/ScavengeSurvive#379]
![sem titulo](https://cloud.githubusercontent.com/assets/24531388/21859453/cc7e941a-d813-11e6-8aa6-aa334f076b26.png)

Not all defenses are appearing in your life.   Without showing how much to destroy.

example: Should appear on the defenses 7/7 5/5  How much to destroy

I'm using version 1193 I do not want to switch to another, if anyone knows of this solution please let me know

**Comment by Southclaws** [comment]
If I remember correctly, this was an issue with SIF not allowing line of sight tests on item labels (or button labels, more specifically) so you just need to adjust that.

Unfortunately I don't really support older versions, this bug has been fixed long ago so I'm closing this.
