### ISSUE TITLE
AddItemToPlayer ordering mismatch (needs a logic overhaul)

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#382]

**Comment by Southclaws** [comment]
I have no idea if this was ever fixed, wasn't this the cause of Y not placing items in bags/inventories properly?

**Comment by viruxe** [comment]
Y key seems to be working fine.

**Comment by Southclaws** [comment]
Pretty sure this should have fixed it, it attempts inventory first then only if that fails it attempts backpack: https://github.com/Southclaws/ScavengeSurvive/blob/master/gamemodes/sss/core/char/backpack.pwn#L259-L263

**Comment by viruxe** [comment]
I've just tested it now and it seems to be working. Need to do further testing though. Test it with the inventory full and etc.

**Comment by NegativeIQ** [comment]
Didnt test these since defenses "overhaul" but in earlier versions it worked fine. If you have space in inventory, it places item into inventory, otherwise it tries backpack.

**Comment by Southclaws** [comment]
Confirmed, still present in `redis` branch.
