### ISSUE TITLE
Pick-up ammo transfer targeting multiple items

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#385]
> [4:37 PM] Prodigy: 2. Ammo bug: I had two MACs on the ground, one with 30 HP bullets and one empty, both close to each other, at a very small distance of a few Cm. With a HP ammo box in my hands, I pressed the "Take/Pick" button over the MAC with 30 bullets and I took 0 bullets from it, then I searched both MACs and they were empty.

**Comment by Virtxmedia** [comment]
Would this cause ammo to vanish from both guns and the ammo box? if so escalate this to a "A". :)

**Comment by Southclaws** [comment]
Possibly, needs testing.
