### ISSUE TITLE
Anti "G-Bug" Code

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#40]
Implement this: http://forum.sa-mp.com/showpost.php?p=2923119&postcount=252 (by Ada32)

``` cpp
new Float:g_Pos[MAX_PLAYERS][3];
new bool:g_EnterAnim[MAX_PLAYERS char];

public OnPlayerEnterVehicle(playerid, vehicleid, ispassenger)
{
    if(ispassenger)
    {
        GetPlayerPos(playerid, g_Pos[playerid][0], g_Pos[playerid][1], g_Pos[playerid][2]);
    }
    return 1;
}

public OnPlayerStateChange(playerid, newstate, oldstate)
{
    if(newstate == PLAYER_STATE_PASSENGER)
    {
        //Check if the player has truly entered the vehicle
        if(!g_EnterAnim{playerid})
        {
            SetPlayerPos(playerid, g_Pos[playerid][0], g_Pos[playerid][1], g_Pos[playerid][2]);
        }
    }
    else if(newstate == PLAYER_STATE_ONFOOT)
    {
        g_EnterAnim{playerid} = false;
    }
    return 1;
}

public OnPlayerUpdate(playerid)
{
    new anim = GetPlayerAnimationIndex(playerid);
    //Check if the animation applied is CAR_getin_LHS/RHS
    if(anim == 1026 || anim == 1027)
    {
        g_EnterAnim{playerid} = true;
    }
    return 1;
}
```

**Comment by Deiity** [comment]
This bugs motorcycles.

**Comment by Southclaw** [comment]
Any explanation as to how?

**Comment by Deiity** [comment]
Since animation isn't same as in vehicle, when for example u enter motorcycle, differente animation is called when u enter on motorcycle. I have downloaded fix which u provide, and its different animation for every type of vehicle, bike,quad, etc,karting...

Can you test yourself? Maybe i failed

**Comment by Southclaw** [comment]
I haven't implemented this yet so I'll test it in a future update (I forgot about this code completely!)

**Comment by Deiity** [comment]
Please let me know if u have any future updates regardless this. Your fix works flawless for cars, but yeah, they cant get on a motorcycle then.
