### ISSUE TITLE
Vehicle Interaction - Crash

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#400]
```
[VEHICLE] lr.old exited MkZ_PVlEPE5GaQ (1) as driver at 286.789123, 2022.934936, 17.346450
ERROR: Player 0 incorrectly flagged as inside button 7610 area, removing.
**Player 0 is not in areas but list isn't empty. Purging list.**
[debug] AMX backtrace:
[debug] #0 native PrintAmxBacktrace () from crashdetect.DLL
[debug] #1 000813bc in ?? (222763932, 244794292) from ScavengeSurvive.amx
[debug] #2 000df39c in ?? (0) from ScavengeSurvive.amx
[debug] #3 000df294 in ?? (0, 16, 0, 0, 0, 0, 12, 0, 16, 0, ... <1073741813 arguments>) from ScavengeSurvive.amx
[debug] #4 00016510 in public OnPlayerKeyStateChange (0, 16, 0) from ScavengeSurvive.amx
```

This pertains to line 269 of `core/vehicle/interact.pwn`

Pawno doesn't seem to be accepting -d3 when compiling.

**Comment by viruxe** [comment]
Another one:

```
[SPAWN] MadMax spawned existing character at 2491.4, 2868.0, 10.4 (307.2)
Vehicle 4 already in NearList for player 0
[debug] AMX backtrace:
[debug] #0 native PrintAmxBacktrace () from crashdetect.DLL
[debug] #1 000813bc in ?? (222760712, 244794280, 244794296) from ScavengeSurvive.amx
[debug] #2 000ded3c in ?? (0, 4) from ScavengeSurvive.amx
[debug] #3 000de714 in ?? (0, 4, 0, 0, 0, 8, 0, 4, 0, 0, ... <1073741813 arguments>) from ScavengeSurvive.amx
[debug] #4 00015824 in public OnPlayerEnterDynamicArea (0, 4) from ScavengeSurvive.amx
[FOCUS] MadMax focused back to game
```

**Comment by Southclaws** [comment]
Pawno sucks, try Sublime with this: https://packagecontrol.io/packages/Pawn%20syntax I forgot how to pass params to pawncc through pawno properly.

All `err` calls now include a `PrintAmxBacktrace` so this isn't actually a crash, it's just a warning to help track down the source of the function call.

That being said, there is an obvious issue with tracking players going in and out of vehicle areas and I am yet to figure it out.

**Comment by viruxe** [comment]
> Pawno sucks, try Sublime with this: https://packagecontrol.io/packages/Pawn%20syntax I forgot how to pass params to pawncc through pawno properly.
Yes intend to do that. Just haven't gotten around to setup sublime for pawn, since I reinstalled the os.

I'll set it up and see if I can get crashdetect to yield something useful.
