### ISSUE TITLE
Safeboxes open when arming tnt near them

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#407]
Either stop them opening or tnt from arming near a safebox. Needs further discussion.

**Comment by Southclaws** [comment]
I think the best option here is to block arming TNT if the return of `GetPlayerButtons` (or whatever it's called) returns anything other than 0.

If the player is near a button to interact with an item or something, prioritise that, beacause TNT has a large blast radius so moving a few metres away won't make a difference.
