### ISSUE TITLE
"Vehicle locked" message shown when passenger tries to exit locked vehicle

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#410]
If when a passenger in a moving vehicle you try to get out of it the following message is displayed: "Door Locked - Use crowbar"

**Comment by Southclaws** [comment]
Is the vehicle locked by the driver? That would make sense since the check is an area check I think. Just need to add a check for if the player is in a vehicle or not.

**Comment by viruxe** [comment]
Correct. Locked by the driver.

**Comment by Southclaws** [comment]
That makes solving this problem much easier.
Just need an `IsPlayerInAnyVehicle` before the call to `OnPlayerInteractVehicle`.
