### ISSUE TITLE
Redis: Accounts

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#418]
Implement and test Redis IO for accounts.

## CRUD operations

- [x] Create
- [x] Get key
- [x] Set key
- [x] GetAccountData(...)
- [x] AccountExists(name[])
- [x] GetAccountPassword(name[], password[MAX_PASSWORD_LEN])
- [x] SetAccountPassword(name[], password[MAX_PASSWORD_LEN])
- [x] GetAccountIP(name[], &ip)
- [x] SetAccountIP(name[], ip)
- [x] GetAccountAliveState(name[], &alivestate)
- [x] SetAccountAliveState(name[], alivestate)
- [x] GetAccountRegistrationDate(name[], &timestamp)
- [x] SetAccountRegistrationDate(name[], timestamp)
- [x] GetAccountLastLogin(name[], &timestamp)
- [x] SetAccountLastLogin(name[], timestamp)
- [x] GetAccountLastSpawnTimestamp(name[], &timestamp)
- [x] SetAccountLastSpawnTimestamp(name[], timestamp)
- [x] GetAccountTotalSpawns(name[], &spawns)
- [x] SetAccountTotalSpawns(name[], spawns)
- [x] GetAccountWarnings(name[], &warnings)
- [x] SetAccountWarnings(name[], warnings)
- [x] GetAccountGPCI(name[], gpci[MAX_GPCI_LEN])
- [x] SetAccountGPCI(name[], gpci[MAX_GPCI_LEN])
- [x] GetAccountActiveState(name[], &active)
- [x] SetAccountActiveState(name[], active)

## Tests

- [x] Register
- [x] Login
- [x] Check "regdate" timestamp
- [ ] Check "lastlog" timestamp updated

**Comment by Virtxmedia** [comment]
Gonna write up test plan when I get back including this list!

**Comment by Southclaws** [comment]
Ready to player test.

**Comment by Virtxmedia** [comment]
Test plan ready to go!

**Comment by Southclaws** [comment]
Updated with more database operations.

**Comment by NegativeIQ** [comment]
With s****, GPCI is being updated every time player restarts samp client or even reconnects server (not sure witch one). So actually keeping list of players GPCI's would be a good thing.

**Comment by Southclaws** [comment]
That was done in `gpci-log` module but it's being replaced anyway. It's not updated every time the player restarts the client as it would be pointless. It changes based on %USERPROFILE% or something similar so changing it requires making a new windows account (or simply modifying packets).

**Comment by NegativeIQ** [comment]
Glad there is gpci log, and what im saying is, they do intercept and modify RPC packets. While having gpci log is quite useful i would rather tie gpci's to accounts (and still keep gpci log). You see when someone install that most known cheat, or any modification of it. Their GPCI automatically changes each time their client restarts (not server browser). So tying that information to account is useful and you could automatically send warnings to admins when lets say players GPCI changed 5 times in last 5 connections after his leave reason was LEFT (not crashed). These way we would have indication that player has installed that cheat and to keep an eye on him. And gpci is generated based on combination of username (profile) and sa-mp (gta) path.

**Comment by Southclaws** [comment]
That's exactly why the log was introduced years ago, but now it's going to be implemented in the extermal app that handles the MongoDB queries, not Pawn.
