### ISSUE TITLE
Redis: Bans

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#419]
Implement Redis for banning players and getting ban info.

## CRUD operations

- [x] Set ban key on player account to 0 or 1 to represent ban state
- [x] Get ban key to check banned state
- [x] Create ban record
- [x] Mark ban record as inactive
- [x] Update ban reason
- [x] Update ban duration
- [x] Get list of bans with offset/limit
- [x] Get ban info

## Tests

- [ ] Ban player - ensure ban recorded in MongoDB
- [ ] Unban player - ensure ban key 0 but ban record still exists
- [ ] Update ban reason - ensure record updated
- [ ] Update ban duration - ensure record updated
- [ ] Ban player, then unban, then ban again - ensure both bans recorded in MongoDB
- [ ] Get list of bans - ensure subsequent bans are present
- [ ] Select ban in list of bans - ensure data matches entered ban info

**Comment by Virtxmedia** [comment]
Gonna write up test plan when I get back including this list!

**Comment by Southclaws** [comment]
Features complete, automated tests passing, ready to do player tests.

**Comment by Virtxmedia** [comment]
Test plan ready to go!
