### ISSUE TITLE
Redis: Admin Core

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#420]
Provide an API to admin level. Stored in account hash.

## CRUD operations

- Set admin level
- Get list of all admins - use Redis cache state, not callback since that data is not updated often

## Tests

- Set player admin level
- Set player admin level then check admin list
- Remove player admin level
- Remove player admin level then check admin list

**Comment by Virtxmedia** [comment]
Gonna write up test plan when I get back including this list!
