### ISSUE TITLE
Redis: Report

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#421]
Reports will be stateless in-cache and only use Redis for data transfer. Setting and getting reports will use a callback mechanism but a single integer of the amount of unread reports will persist in the cache for admin login notifications.

## CRUD operations

- [ ] Create report
- [ ] Delete report - only marks as inactive and removes from List aggregations
- [ ] Delete reports of specific user
- [ ] Delete reports that are read
- [ ] Set report as read
- (all above must update `__unread` when called)
- [ ] Get number of unread reports
- [ ] List reports with offset/limit pagination
- [ ] Get report info

## Tests

- [ ] Report player (report type or interface route doesn't matter)
- [ ] Delete report
- [ ] Delete all reports of player
- [ ] List reports - ensure previous non-deleted reports are present
- [ ] View specific report info

**Comment by Virtxmedia** [comment]
Gonna write up test plan when I get back including this list!
