### ISSUE TITLE
Item loot spawns that are missing or incorrect

### ISSUE THREAD

**Issue by Virtxmedia** [Southclaws/ScavengeSurvive#422]
**Reported by:**
 Dogmeat

**Description:**
Brass Knuckles and Batons not in spawn tables, combat knife not in military/survivor spawns but seem common in civilian (12%!)

These items wont spawn..... or will spawn in the wrong place.

**Link:**

https://github.com/Southclaws/ScavengeSurvive/blob/38dea00cddcf78e691b654f0f0e7a2056a3d5f0d/scriptfiles/loot/world_survivor.ltb

**Comment by Southclaws** [comment]
The server he's testing on probably has a different loot setup. This will need to be confirmed on the main test server once it's ready.

**Comment by Virtxmedia** [comment]
1. I can't add labels :(

2. He been reading the files you gave him, if this is confirmed it would be a B most likely.

**Comment by Southclaws** [comment]
Reassigning this to an Epic to list items that are missing from spawns or in the wrong place.

**Comment by Virtxmedia** [comment]
Running a test plan for this could be difficult, to check spawn rates in an actual playing environment. Depending on issues this could go through to release before we can fix. I feel a lot of issues like this would only be truly testable on release.

**Comment by NegativeIQ** [comment]
Why not just loop thru items and generate some kind of list of spawned items in percents?

**Comment by Southclaws** [comment]
I plan to do exactly that, it's already partially happening here: https://github.com/Southclaws/ScavengeSurvive/blob/98ecb24e8a03402fdd9b930b40966dfaf6fd1d0e/gamemodes/sss/world/world.pwn#L136 which prints the amount of items spawned.

What I will probably do is write a small script that loads the .ltb files and runs them through the same algorithms as the Pawn code then simulates a few thousand loot spawn cycles, averages the results and throws back an average spawn rate of each item which can then be compared to the values in the .ltb files with a margin of error to allow for randomness.
