### ISSUE TITLE
Re-entering gender-select screen results in no black background

### ISSUE THREAD

**Issue by Virtxmedia** [Southclaws/ScavengeSurvive#433]
Reproduction steps:
1. Load into SA:MP as new player
2. While timer counts down on welcome menu appears, spam click the countdown button.
3. Once in the tutorial from that menu type /exit.
4. Observe gender select menu.

Result:  Camera facing sky on gender select menu. This causes no other issues apart from the camera is shown facing the sky instead of the black screen.

**Comment by viruxe** [comment]
Isn't this some sort of conflict from the s0beit detection algorithm?

**Comment by NegativeIQ** [comment]
If the player is spawned at that moment then possibly yes.

**Comment by Southclaws** [comment]
Nothing to do with that, just bad UI placement!
