### ISSUE TITLE
Template based pre-compile

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/ScavengeSurvive#441]
An idea I've had knocking around for well over a year, the time has come where this might be very useful -- not only for SS but as a general tool for compiling Pawn.

Looking at Golang's text/template library, it wouldn't be at all difficult to create a rather simple templating pre-compile step for Pawn code. It's not a new concept in the Pawn community and has been done before.

This project would be implemented purely in Go using the standard library and compile down to a single binary that would be run before `pawncc` as a form of middleware. At first I'll focus features on SS and see what ends up being specific to SS and what can be made generic so the tool can be used elsewhere.

The main use cases I can think of are:
- eliminating the need to use runtime functions to get call site information - for logging
- more powerful conditional macros
- code generation - I'm thinking of non-hacky ways of doing certain things that YSI does (cc @y-less @misiur)

Aside from templates, some regex based matching could be a useful replacement for y_hooks. I love YSI and it's very useful but I often hear people comparing it to C++ Boost libraries (fair comparison) and when people only want to use a single feature (such as the ever-useful y_hooks) they sometimes don't want to bring in an entire framework.

A quick concept for a hooks system I was playing with:

Input:
```pawn
hook event() { }
hook event() { }
```
Output:
```pawn
public event() {
    event_01();
    event_02();
}
forward event_01(); public event_01() { }
forward event_02(); public event_02() { }
```
Which is kind of how y_hooks does it, but the difference is this would be a pre-compile stage which outputs pure Pawn.

Another idea is grabbing file/line information for logging.

Input:
```pawn
warn("player not connected");
```
Output:
```pawn
warn("[sss/core/player/core.pwn:52] FunctionName: player not connected");
```
Which I could do by manipulating the output of `PrintAmxBacktrace` at runtime but the template solution would eliminate the need to run string manipulations at runtime just to get some static call site info.

And finally, fake inlining. The advantage here being that no special code would be required for external libraries to implement in order to support this style of "inline" functions. All you'd need to do is use the standard YSI `using inline Function` and `inline Function` syntax and the pre-compiler could do the code generation automatically and output valid Pawn code with generated callback names.

Input:
```pawn
    ...
    inline Response(...) {
        // dialog code
    }
    Dialog_ShowCallback(using inline Response, ...);
}
```
Output:
```pawn
    Dialog_ShowCallback("__inline_01", ...);
}
forward __inline_01(...); public __inline_01(...) {
    // dialog code
}
```

--

Most of this comes from one of my old proposals to write a static analysis tool for Pawn. I was originally doing this in Python but later decided that 1. that's not the correct tool for the job and 2. it's a much more complex task if I wanted to fully support all language features and successfully parse any new syntax introduced by YSI such as foreach, foreign functions, iterators, hooks and more.

This project will be much simpler than static analysis but I may actually go back to that idea in the future.

**Comment by NegativeIQ** [comment]
Custom data types and function overloading would be dope. For example we define PlayerPos type, and GetPlayerPos can be overloaded to return 3 floats or PlayerPos (in case with PlayerPos it would also return rotation).

**Comment by Southclaws** [comment]
Function overloading would be rather easy, but it would require codebase-wide changes rather than changes to a small section of code (similar to hooking, in a way).

**Comment by Southclaws** [comment]
I think most of this requires some kind of code parsing so I will likely write a very basic lazy parser first (something that can deal with odd syntax like YSI but just ignore the stuff it doesn't understand so a very basic AST of function calls and variables is built).

**Comment by Y-Less** [comment]
I've often thought about this, and would love to see it!  I'm also aware of the problems people have with pulling in all of YSI (it has got VASTLY better over the years, but could probably still be improved further).

**Comment by Misiur** [comment]
I started to write tokenizator and AST generator in haxe for my own purposes, but gave up when I remembered that YSI exists. Best of luck, I'll be keeping an eye on this project to learn a thing or two

**Comment by Y-Less** [comment]
Yeah, sorry about that... :X

**Comment by Southclaws** [comment]
I'm sure the pawncc precompiler output can help with that!

**Comment by Dayvison** [comment]
i going to wait for this sure this will help me http://forum.sa-mp.com/showthread.php?p=3871710#post3871710

**Comment by Southclaws** [comment]
Yes this could help with that!

**Comment by Y-Less** [comment]
https://github.com/oscar-broman/Prawn

Don't know if this is of any help.

**Comment by Southclaws** [comment]
Oh damn I remember this! I never really looked into it though since there wasn't much documentation and I didn't fancy installing the dependencies.

One reason why I chose Go as the cross-platform capability is really impressing me so far!

**Comment by Y-Less** [comment]
I forgot as well, just found it while looking through my list of stars for something else entirely.
