### ISSUE TITLE
Ammo item bug

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#451]
How can I fix this?

![bug](https://cloud.githubusercontent.com/assets/24555369/26130029/5deba7d2-3a82-11e7-84e8-58c697708856.jpg)

**Comment by kadaradam** [comment]
Learn pawn

**Comment by KoloradoPlay** [comment]
?

**Comment by Southclaws** [comment]
Fixed on redis branch, pending merge.
