### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#468]
What does that mean ?

![distance](https://user-images.githubusercontent.com/24555369/28748331-35017e80-748b-11e7-8dc0-9a8d390755f2.png)

**Comment by Southclaws** [comment]
That means a player's camera is 174 metres away from their character model. They're either paused (though I'm sure I added a check for this) or they are using camera hacks.

Don't ban based on this (that's why it's not a proper report yet) just use it as a reason to investigate a player a bit more.

**Comment by KoloradoPlay** [comment]
ok
