### ISSUE TITLE
Debug log

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#469]
[LoadVehiclesFromFolder] Loading vehicles from: 'vspawn/'...

Explicit vehicle type 'Coach' is invalid in 'vspawn/LV_Airport.vpl':11

[debug] AMX backtrace:
[debug] #0 native PrintBacktrace () from crashdetect.DLL
[debug] #1 000a381c in err (text[]=@10543d3c "Explicit vehicle type '%s' is invalid in '%s':%d", ... <3 arguments>) at sss/utils/logging.pwn:83
[debug] #2 0011a648 in LoadVehiclesFromFile (file[]=@12adb1ac "vspawn/LV_Airport.vpl") at sss/core/vehicle/spawn.pwn:277
[debug] #3 00119390 in LoadVehiclesFromFolder (foldername[]=@10543438 "vspawn/") at sss/core/vehicle/spawn.pwn:132
[debug] #4 00118c94 in ?? (... <1073741823 arguments>) at sss/core/vehicle/spawn.pwn:72
[debug] #5 0001558c in public ScriptInit_OnGameModeInit () at C:\include\YSI\..\YSI_Coding\..\YSI_Data\..\YSI_Coding\..\YSI_Internal\y_cgen.inc:30
[debug] #6 000088ac in public SSCANF_OnGameModeInit () at C:\include\YSI\..\YSI_Core\..\YSI_Internal\..\YSI_Server\y_scriptinit.inc:184
[debug] #7 00001f34 in public main_OnGameModeInit () at C:\include\sscanf2.inc:205
[debug] #8 00000b68 in ?? () at C:\gamemodes\ScavengeSurvive.pwn:96

Explicit vehicle type 'Police Maverick' is invalid in 'vspawn/SF_City2.vpl':16

[debug] AMX backtrace:
[debug] #0 native PrintBacktrace () from crashdetect.DLL
[debug] #1 000a381c in err (text[]=@10543d3c "Explicit vehicle type '%s' is invalid in '%s':%d", ... <3 arguments>) at sss/utils/logging.pwn:83
[debug] #2 0011a648 in LoadVehiclesFromFile (file[]=@12adb1ac "vspawn/SF_City2.vpl") at sss/core/vehicle/spawn.pwn:277
[debug] #3 00119390 in LoadVehiclesFromFolder (foldername[]=@10543438 "vspawn/") at sss/core/vehicle/spawn.pwn:132
[debug] #4 00118c94 in ?? (... <1073741823 arguments>) at sss/core/vehicle/spawn.pwn:72
[debug] #5 0001558c in public ScriptInit_OnGameModeInit () at C:\include\YSI\..\YSI_Coding\..\YSI_Data\..\YSI_Coding\..\YSI_Internal\y_cgen.inc:30
[debug] #6 000088ac in public SSCANF_OnGameModeInit () at C:\include\YSI\..\YSI_Core\..\YSI_Internal\..\YSI_Server\y_scriptinit.inc:184
[debug] #7 00001f34 in public main_OnGameModeInit () at C:\include\sscanf2.inc:205
[debug] #8 00000b68 in ?? () at C:\gamemodes\ScavengeSurvive.pwn:96

**Comment by Southclaws** [comment]
Please do not post logs without ``` wrapped around them, it creates relationships to other issues because of the # characters. Check this: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
