### ISSUE TITLE
Server crash explosive

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#470]
deleted

**Comment by KoloradoPlay** [comment]
Debug log:

[debug] Run time error 6: "Invalid instruction"
[debug]  Unknown opcode 0x78 at address 0x00000000
[debug] AMX backtrace:
[debug] #0 00000069 in public OnItemHitPointsUpdate () at <unknown file>:0
[debug] #1 native CallLocalFunction () from ScavengeSurviveBR.exe
[debug] #2 0007e4bc in SetItemHitPoints (itemid=0, hitpoints=-1) at C:\Users\Nicolas\Desktop\S and S DayZ\pawno\include\SIF\Item.pwn:1586
[debug] #3 000f4d58 in _IterateItemDmg (i[]=@0ed28008 "", s=1233912064, c=-457437226, o=7, d=2) at sss/core/world/explosive.pwn:573
[debug] #4 000f4c7c in public @Yj:_IterateItemDmg@_yT (__r=0, i=62162889, s=256, c=4, o=4, d=2) at sss/core/world/explosive.pwn:568

**Comment by Southclaws** [comment]
(Please use ``` for code! Do not simply paste logs in.)

Looks like memory corruption, it could also be YSI getting messed up by something. I can't really say to be honest. That function is very dangerous though looking at it now and it really needs some validation on the input parameters.

Maybe @Y-Less can chime in on the possible cause of the "Invalid instruction" business but I'm just going to assume memory corruption due to some other (probably unrelated) part of code.

**Comment by KoloradoPlay** [comment]
One piece of information: this only happens when the explosive is crafted on the workbench. When used / additem this does not happen.
