### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#474]
What happens if I set `MAX_PLAYERS 500` without gamemode? Can this cause a memory problem?

**Comment by kadaradam** [comment]
No, you have to set the annoying variable to `true`.

**Comment by KoloradoPlay** [comment]
ok

**Comment by Southclaws** [comment]
I wouldn't advise it but you may as well try.

**Comment by KoloradoPlay** [comment]
This is for zombie NPCs
