### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by KoloradoPlay** [Southclaws/ScavengeSurvive#475]
# This happened when I used YSI 4.0

![sla](https://user-images.githubusercontent.com/24555369/29381246-e9224932-829e-11e7-8412-35be7e051b6a.png)

**Comment by KoloradoPlay** [comment]
?

**Comment by Y-Less** [comment]
This isn't the YSI repository, but either delete the sprintf in YSI or strlib - I added it recently but probably shouldn't have.

**Comment by Southclaws** [comment]
A compile-time flag could solve this collision nicely!

**Comment by Southclaws** [comment]
@KoloradoPlay please don't name issues nonsense like "asd" as I have a tendency to ignore them as spam and insta-close! Even just a copy-paste of the error would be better than a keyboard smash.

**Comment by KoloradoPlay** [comment]
Sorry southclaw, it was not for wanting
