### ISSUE TITLE
y_va using old variadic style

### ISSUE THREAD

**Issue by BrasilianZ** [Southclaws/ScavengeSurvive#476]
Hello? Can you send me the YSI link that should be used in Scavenge? When I use https://github.com/Misiur/YSI-Includes, things like these happen:

```
================================================================================
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
    Southclaw's Scavenge and Survive
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
        Copyright (C) 2016 Barnaby "Southclaw" Keene
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
        This program comes with ABSOLUTELY NO WARRANTY; This is free software,
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
        and you are welcome to redistribute it under certain conditions.
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
        Please see <http://www.gnu.org/copyleft/gpl.html> for details.
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
================================================================================
Number of vehicle models: 23

*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
*** YSI Warning: Bare `___` usage found - make sure it is a function parameter.
```

**Comment by Y-Less** [comment]
I think that might be this:

https://github.com/Misiur/YSI-Includes/issues/196

The new y_va design removed the need for a custom `va_formatex` function - I didn't know that third-party y_va function existed until that other issue came up.  The fix is basically:

```pawn
#define va_formatex formatex
```

**Comment by Y-Less** [comment]
I'm going to add this to YSI.  It's not perfect, but will detect functions with the old `va_:STATIC_ARGS` code (this is the only other function I know of written in y_va style but not in y_va) and give an unused variable warning on that line.

```pawn
#define va_:STATIC_ARGS STATIC_ARGS, please_upgrade_va_formatex
```

**Comment by Y-Less** [comment]
Fixed in YSI.

**Comment by KoloradoPlay** [comment]
Thank you very much!

**Comment by Y-Less** [comment]
I'm going to add running the SS tests in to my YSI testing.  The YSI tests are good for internal consistency, but often miss compatability issues with other code.  This is probably the best public YSI user with additional code in to test for that sort of thing.

**Comment by Southclaws** [comment]
I must run through the latest YSI changes - I've not touched Pawn for a while but there's still a lot I want to do with this project so hopefully it'll continue to be a good test bed!

Ontopic: I realised that I don't actually use any of the custom specifiers provided by Slice's formatex so I might just switch to YSI for that. I'll dive into the dependencies one day and have a better look. Thanks!

**Comment by Southclaws** [comment]
Resolved in recent merge, also I realised that I *do* use Slice's custom specifiers, quite a lot actually so I left it in and so far, hasn't seemed to cause any issues with the new y_va.
