### ISSUE TITLE
Restart/Inline bug

### ISSUE THREAD

**Issue by BrasilianZ** [Southclaws/ScavengeSurvive#477]
After a while with the server on, after restarting, no player can log in to the server, clicking "Login" nothing happens. What can cause this?

**Comment by Southclaws** [comment]
I've not come across this before but I've seen reports of a similar issue - I moved to easyDialog in the redis version because I was skeptical of the y_inline magic, it seemed to resolve weird bugs but I also removed sqlitei at the same time so it's difficult to say what was the cause.

**Comment by KoloradoPlay** [comment]
I solved using this:

`#define YSI_NO_HEAP_MALLOC`

**Comment by Southclaws** [comment]
Interesting, I've not used that flag before and I have no idea what it actually does.

What version of SS and YSI are you using? (or, since YSI only recently started being versioned, a date of when you downloaded it would be more useful)

cc @Y-Less - might be relevant to you

**Comment by Y-Less** [comment]
Actually, YSI has sort of have versions for a long time, they just made no sense and were totally useless.  That switches y_malloc from using a hack to allocate memory on the heap to allocating memory from a large global variable.  I actually thought it was you who first noticed the problem with inlines eventually breaking after several restarts, but maybe I'm mis-remembering.

**Comment by Southclaws** [comment]
Oh that actually rings a bell, I think I did report the original back when I was moving from YSI3 to YSI4... either that or something related to dialogs.

Anyway, I'll leave this open so once I get back to developing this project I can do my own testing and add it to the source if necessary.

**Comment by KoloradoPlay** [comment]
I am using SS and YSI both in the latest version

**Comment by KoloradoPlay** [comment]
Por que você bota ` [state] Confirmation Needed` ?

**Comment by Y-Less** [comment]
Yeah, I'm not surprised the heap method had problems. It actually uses a bug in the VM itself to get a chunk of the heap and overwrite the VM's own pointers to it so that it can't reclaim the memory when the current public finishes (otherwise it would constantly clean up in use memory, since the heap is only meant to be temporary).

**Comment by Y-Less** [comment]
I should try restore the heap after the mode ends, see if that helps.
