### ISSUE TITLE
Server freeze when logging in

### ISSUE THREAD

**Issue by Mecaurio** [Southclaws/ScavengeSurvive#481]
Most of the times it happened this is what I did:

1. Open server, connect to the SA-MP server while it loads.
2. For some reason, since the SS data is still loading the server holds on my connection, then calls it invalid and kicks me.
3. Re-connect after everything is loaded but after I press the login button the server freezes.

**Comment by Southclaws** [comment]
Which build/branch did this happen in?

If not `redis` then it doesn't matter, that branch will be replaced with the `redis` branch soon so I'll close this.

If it was `redis` then I'll keep this open for details.

**Comment by Mecaurio** [comment]
Build 1769.

Not sure if it's redis or not. Just wondering if someone else has the same problem.

**Comment by Southclaws** [comment]
Ah okay, that's the old branch so I'll close this for now and if it still happens on the new branch, I'll reopen. Thanks for reporting anyway!
