### ISSUE TITLE
Vehicle save

### ISSUE THREAD

**Issue by BrasilianZ** [Southclaws/ScavengeSurvive#482]
Can you explain to me how the vehicle rescue works?

I am having a problem on my server:

Some vehicles do not save or disappear in restart .. even sometimes using / vsave on

**Comment by BrasilianZ** [comment]
As far as I understand, the server saves only 1 vehicle per player. I wanted to increase that number to 4. Is it possible?

**Comment by Southclaws** [comment]
Build 1192 had a rare bug where vehicles would not save. I can't remember for later versions and the `redis` branch does not support vehicle saving.

The server does save one vehicle per player and it would not be trivial to change this, you'd probably have to rip out the entire player-vehicle module and rewrite it to use a keying method and stuff. It would be pretty complicated to be honest and, in my opinion in terms of game balance, not good for gameplay.

**Comment by BrasilianZ** [comment]
Many players complain that vehicles are fading

**Comment by Southclaws** [comment]
It'll be resolved when the redis branch gets merged.

**Comment by BrasilianZ** [comment]
ok
