### ISSUE TITLE
Compile 

### ISSUE THREAD

**Issue by BrasilianZ** [Southclaws/ScavengeSurvive#491]
Can you give me a brief explanation of how to compile gamemode in Linux VPS ubuntu? I'm compiling without windows but it takes too long

**Comment by Southclaws** [comment]
Have you read the recently updated readme file? I detailed the compilation process there.

**Comment by BrasilianZ** [comment]
I had read it, but it did not help me much :(

I tried to install zeex compiler on my vps but it does not seem to work on ubuntu

**Comment by Southclaws** [comment]
I use it on Ubuntu successfully - it takes some extra steps. you should open a forum topic do discuss details though (either [this forum](https://forum.southcla.ws) or [that forum](http://forum.sa-mp.com)) as this isn't really the place.
