### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BrasilianZ** [Southclaws/ScavengeSurvive#495]
`BanPlayer(playerid, reason[], byid, duration)`

Is this `duration` in seconds?

**Comment by Southclaws** [comment]
Yes.

Please don't post questions here. I've said before.

Post questions on:

- [Discord](http://dc.southcla.ws)
- [Forum](https://forum.southcla.ws)

**Comment by BrasilianZ** [comment]
ok, sorry
