### ISSUE TITLE
Gamemodetext

### ISSUE THREAD

**Issue by BrasilianZ** [Southclaws/ScavengeSurvive#501]
If I change the gamemodetext my server stops appearing in the "Internet" tab of SA-MP?

**Comment by Southclaws** [comment]
If you read the note next to the gamemode, you'll see that I don't want people to change it:

> I'd appreciate if you left my credit and the proper gamemode name intact!
> Failure to do this will result in being blacklisted from the server list.
> And I'll be less inclined to help you with issues.
> Unless you have a decent reason to change the gamemode name (heavy mod)
> I'd still like to be credited for my work. Many servers have claimed
> they are the sole creator of the mode and this makes me sad and very
> hesitant to release my work completely free of charge.

**Comment by BrasilianZ** [comment]
My server is not showing up on the "internet" tab. For some reason this only happens with the GM Scavenge Survive. What can it be?

**Comment by BrasilianZ** [comment]
?

**Comment by Southclaws** [comment]
I don't know, that's an issue with the internet list or your server configuration. The gamemode script doesn't have any control over listing announcement aside from the gamemode name.
