### ISSUE TITLE
include map 

### ISSUE THREAD

**Issue by lukassimoes** [Southclaws/ScavengeSurvive#510]
C:\Users\Venda\Desktop\sap\pawno\include\language.inc(14) : fatal error 100: cannot read from file: "map"

Southclaw I already looked everywhere and did not find this include, can you send me the link? Thanks you

**Comment by Southclaws** [comment]
Use sampctl to install [dependencies](https://github.com/Southclaws/sampctl/wiki/Dependencies), they are listed in `pawn.json`.
