### ISSUE TITLE
sampctl 

### ISSUE THREAD

**Issue by lukassimoes** [Southclaws/ScavengeSurvive#511]
southclaws my sampctl is giving this warning, why? > WARN: failed to ensure package github.com/sampctl/samp-stdlib: failed to ensure dependency from cache: exec: "git": executable file not found in %PATH%

**Comment by Y-Less** [comment]
> git [...] not found

**Comment by lukassimoes** [comment]
i have installed git, What do I do, I'll do some link if possible.

**Comment by lukassimoes** [comment]
solved, I restarted the program, thanks you for attention

**Comment by Southclaws** [comment]
I'm glad you solved your issue, just FYI this is the Scavenge and Survive repository, sampctl is here: https://github.com/Southclaws/sampctl/

**Comment by lukassimoes** [comment]
thanks you southclaws
