### ISSUE TITLE
Log Flood

### ISSUE THREAD

**Issue by BrasilianZ** [Southclaws/ScavengeSurvive#512]
(Sorry my bad english)

After a while with the server turned on, it kind of stayed in an infinite loop and no one could get on the server. The only solution I found was to change the options in server.cfg, from 30 to 100:

onfoot_rate 100
incar_rate 100
weapon_rate 100

The server stopped with the infinite loop, but started to print this in server_log.txt:

itemwepaonid 38, calibre 2, ammotype 2
itemwepaonid 38, calibre 2, ammotype 2
itemwepaonid 38, calibre 2, ammotype 9
itemwepaonid 41, calibre 0, ammotype 7
itemwepaonid 61, calibre 10, ammotype 15
itemwepaonid 38, calibre 2, ammotype 9
itemwepaonid 59, calibre 4, ammotype 4
itemwepaonid 59, calibre 4, ammotype 4
itemwepaonid 61, calibre 10, ammotype 15
itemwepaonid 42, calibre 0, ammotype 0
itemwepaonid 61, calibre 10, ammotype 15
itemwepaonid 61, calibre 10, ammotype 15
itemwepaonid 59, calibre 4, ammotype 4
itemwepaonid 59, calibre 4, ammotype 4
itemwepaonid 35, calibre 0, ammotype 7
itemwepaonid 61, calibre 10, ammotype 15
itemwepaonid 59, calibre 4, ammotype 4
itemwepaonid 59, calibre 4, ammotype 4
itemwepaonid 38, calibre 2, ammotype 2
itemwepaonid 44, calibre 3, ammotype -1
itemwepaonid 38, calibre 2, ammotype 8
itemwepaonid 48, calibre 6, ammotype 5
itemwepaonid 43, calibre 3, ammotype -1
itemwepaonid 38, calibre 2, ammotype 2

**Comment by Southclaws** [comment]
This is probably some debug print I left in during development.

Keep in mind this codebase is abandoned and a complete mess so there are things like this all over the place.
