### ISSUE TITLE
Go packages problem

### ISSUE THREAD

**Issue by MBaltz** [Southclaws/ScavengeSurvive#520]
Hello Southclaws, i've a problem with go packages.

This url dosen't works
`github.com/Southclaws/sampctl/pkgcontext`
https://github.com/Southclaws/ScavengeSurvive/blob/4c88765000ba3d5cdf1faba853e7346bf360e87d/runner/main.go#L11

I tink it was moved to:
`github.com/Southclaws/sampctl/rook`

---

**Comment by Southclaws** [comment]
that's weird, builds fine here 

CI downloads some version so that's valid https://github.com/Southclaws/ScavengeSurvive/runs/1316921234?check_suite_focus=true#step:4:10

**Comment by MBaltz** [comment]
## Thank you.
### I was using a old golang version.
__I just use the most recent version to golang, and it works!__

`00:31:45.847	INFO	starting blocking process`
