### ISSUE TITLE
Guns - Don't loose bullets

### ISSUE THREAD

**Issue by VIRUXE** [Southclaws/ScavengeSurvive#529]
Guns don't loose bullets when shot at defenses.

**Comment by Southclaws** [comment]
This is probably because OnPlayerWeaponShot doesn't get called when shot at dynamic objects or something. I never fixed it because it wasn't that important.

**Comment by VIRUXE** [comment]
That's what I thought. That an event of some kind just wasn't being triggered. Should be an easy fix.
