### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by DJShocker** [Southclaws/ScavengeSurvive#631]
Can't build at all. 
```failed to compile package entry: exit status 3221225477```

**Comment by Southclaws** [comment]
That's an access violation, likely unrelated to this project but instead indicates an issue with either sampctl or pawnc.

Search the error on the sampctl or pawn compiler issues.

**Comment by DJShocker** [comment]
Well, I can compile the one when I clone the repository as a zip, but when I download the latest from the release, it gives me that error.
