### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by amrulhadi** [Southclaws/ScavengeSurvive#632]
Please help me, every time I run the server via Ubuntu VPS, an error appears like this?, I try to run the server on windows via sublime text, it's safe, no problem appears, please help.
![20220303_133713](https://user-images.githubusercontent.com/97217482/156510957-f844ae1c-060b-45ca-8c3a-5297ca554a74.png)

**Comment by Southclaws** [comment]
You're missing a dependency, use sampctl to install everything.
