### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#73]
Everytime an haxor manages to get inside a base you never know where they put the stolen boxes and if they took anything from those boxes. So, taking snapshots would be a way to log/register the boxes and their contents every time the server restarts so admins can retrieve all the illegally stolen loot.
- search for box containers inside the list of detection fields
- "print" the contents of those containers:
  -- for example
  -- a largebox is full of tnt
  -- just print out "10 TNT"

**Comment by Southclaw** [comment]
Snapshots will now be written as a Python script that zips the data directory on every restart.
